packages:
  - '.'

ignoredBuiltDependencies:
  - chromedriver
  - core-js
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - react-markdown
  - scratch-blocks
  - scratch-extension-editor
  - scratch-vm
