/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./userstyle.css";
import _css2 from "!css-loader?{\"esModule\":false}!./hide-labels.css";
import _css3 from "!css-loader?{\"esModule\":false}!./sprite-properties.css";
import _css4 from "!css-loader?{\"esModule\":false}!./gui.css";
import _asset from "!url-loader?{\"esModule\":false}!./close.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "hide-labels.css": _css2,
  "sprite-properties.css": _css3,
  "gui.css": _css4,
  "close.svg": _asset,
};
