name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install Dependencies
      run: pnpm install --ignore-scripts

    - name: Run prepublish script
      run: node scripts/prepublish.mjs

    - name: Build GUI
      run: pnpm run build
        
    - name: Run Tests
      run: pnpm run test:unit